version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo_prod}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo} -d ${POSTGRES_DB:-odoo_prod}"]
      interval: 30s
      timeout: 10s
      retries: 3

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: t29-odoo:latest
    container_name: odoo-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      USER: ${ODOO_DB_USER:-odoo}
      PASSWORD: ${ODOO_DB_PASSWORD:-secure_password}
      DATABASE: ${POSTGRES_DB:-odoo_prod}
      ADMIN_PASSWORD: ${ODOO_ADMIN_PASSWORD:-admin123}
    volumes:
      - odoo-data:/var/lib/odoo
      - ./logs:/var/log/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
    ports:
      - "8069:8069"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:1.25.2-alpine
    container_name: odoo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - odoo
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: odoo-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backup:
    image: postgres:15-alpine
    container_name: odoo-backup
    restart: "no"
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-secure_password}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    depends_on:
      - db
    networks:
      - odoo-network
    command: /bin/sh -c "while true; do sleep 86400; done"

volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
  redis-data:
    driver: local

networks:
  odoo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
