version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.426.1-lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins:/var/jenkins_home/casc_configs
      - ./logs:/var/jenkins_home/logs
      - ./scripts:/var/jenkins_home/scripts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

  docker-in-docker:
    image: docker:24.0.6-dind
    container_name: docker-in-docker
    restart: unless-stopped
    privileged: true
    volumes:
      - docker-data:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_DRIVER=overlay2
    networks:
      - jenkins-network

  registry:
    image: registry:2.8.2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    networks:
      - jenkins-network

  nginx:
    image: nginx:1.25.2-alpine
    container_name: jenkins-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - jenkins
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local
  docker-data:
    driver: local
  registry-data:
    driver: local

networks:
  jenkins-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
